### ISSUE TITLE
Demo failes on chromium 53

### ISSUE THREAD

**Issue by nxdefiant** [EESC-LabRoM/rosweb#1]
Because of mixed http/https:

```
roslib.min.js:1 Mixed Content: The page at 'https://eesc-labrom.github.io/rosweb/#' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.10:9090/'. This request has been blocked; this endpoint must be available over WSS.d.connect @ roslib.min.js:1RosEvents.Connect @ ros.ts:31dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
roslib.min.js:1 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

**Comment by marcoarruda** [comment]
Unfortunately I can't set github.io page to use http protocol.

Please try it on this another address: [http://labrom.eesc.usp.br/rosweb/](http://labrom.eesc.usp.br/rosweb/), which I'll update on readme.
It's important to say also that there are some problems with Microsoft Edge and Firefox. For instance I'm developing only for google chrome, but it worked on Chromium on my tests.

Please, feel free to contribute!

Thanks!

**Comment by nxdefiant** [comment]
Demo works on labrom.eesc.usp.br, thanks.
