### ISSUE TITLE
Missing files for local deploy!

### ISSUE THREAD

**Issue by letsdoitagain** [EESC-LabRoM/rosweb#12]
Hello, following files are missing from the git repo:

1: main.css   http://labrom.eesc.usp.br/rosweb/main.css

2: widgets.css  http://labrom.eesc.usp.br/rosweb/widgets.css

**Comment by letsdoitagain** [comment]
the js files are misplaced and need to be updated for index.html to work. Please correct the structure.:)

**Comment by nageshpindi** [comment]
Hello,
         Does it works locally instead of running in browser.....?
