### ISSUE TITLE
Not able to drag the widgets.

### ISSUE THREAD

**Issue by WLwind** [EESC-LabRoM/rosweb#15]
I'm using Chromium browser and loads the working demo page.I can connect to the rosbridge_websocket but when I add a widget, a notification comes to me from the browser "Error: ROSWeb may not be connected to a RosBridge WebSocket server". And the red ERRORs comes to the terminal like this:

[ERROR] [1562149470.765854]: Error processing request: 'module' object has no attribute 'get_topics'
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 625, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/kinetic/lib/rosapi/rosapi_node", line 97, in get_action_servers\n    topics = proxy.get_topics(rosapi.glob_helper.topics_glob)\n', "AttributeError: 'module' object has no attribute 'get_topics'\n"]
[ERROR] [1562149470.766300]: [Client 6] [id: call_service:/rosapi/action_servers:4] call_service ServiceException: service [/rosapi/action_servers] responded with an error: error processing request: 'module' object has no attribute 'get_topics'

And the widget that I have just added is not able to be draged around. Do you have any ideas to solve this problem?

**Comment by RalphCodesTheInternet** [comment]
Any solution yet?

**Comment by marcoarruda** [comment]
Fixed on commit https://github.com/EESC-LabRoM/rosweb/commit/c94a181288450af3fcbf0a7240270c41a7c881f9
