### ISSUE TITLE
Add documentation how to install and build yourself

### ISSUE THREAD

**Issue by plieningerweb** [EESC-LabRoM/rosweb#2]
I would love to help / contribute, especially because image subscription did not work for me

**Comment by marcoarruda** [comment]
Hi @plieningerweb,
Your help will be appreciated!

Just to make sure, are you running the web_video_server ROS package? (http://wiki.ros.org/web_video_server)
[It is not compatible with ROS Kinetic!]

**Comment by plieningerweb** [comment]
Ah ok, I must have overlooked the Contributions link / Section in the README.
So now I know how to install the development version :)

Our Problem seems to be the web_video_server right now, because it does not Stream our camera. I will open a ticket there...

**Comment by marcoarruda** [comment]
I don't know what type of message you are trying to stream, but it is important to notice that once I had problem with a compressed image topic.
